name: CUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C compiler
      run: sudo apt-get update && sudo apt-get install -y gcc libcunit1 libcunit1-dev

    - name: Build and run tests
      run: |
        make test
